# Generated by Django 3.2.14 on 2022-07-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CelestialBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('a', models.FloatField()),
                ('e', models.FloatField()),
                ('i', models.FloatField()),
                ('w', models.FloatField()),
                ('node', models.FloatField()),
                ('tp', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_type', to='orbit_display.celestialbodytype')),
            ],
        ),
    ]
